import type { Metadata } from 'next'

import '@/app/(app)/globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Provider from '@/trpc/Provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark'>
      {/* added grid rows so the footer will always be aligned to the bottom of screen */}
      <body className='grid h-full min-h-lvh w-full grid-rows-[1fr_auto]'>
        <Provider>
          <Navbar />
          <main className='py-80 md:py-128'>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
