import configPromise from '@payload-config'
import { SiteSetting } from '@payload-types'
import { getPayloadHMR } from '@payloadcms/next/utilities'
import type { Metadata } from 'next'

import '@/app/(app)/globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Provider from '@/trpc/Provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const payload = await getPayloadHMR({ config: configPromise })
  const initData = (await payload.findGlobal({
    slug: 'site-settings',
    draft: false,
  })) as unknown as SiteSetting

  return (
    <html lang='en' className='dark'>
      {/* added grid rows so the footer will always be aligned to the bottom of screen */}
      <body className='grid h-full min-h-lvh w-full grid-rows-[1fr_auto]'>
        <Provider>
          <Navbar data={initData} />
          <main className='py-80 md:py-128'>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
